### ISSUE TITLE
Way to hide bots, specific users and/or ASCII art in chat

### ISSUE THREAD

**Issue by lesingebleu** [lay295/TwitchDownloader#1078]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Sometimes chat is filled with ASCII art, some of it being NSFW. Both chatters and bots spam it sometimes. They take up a lot of space on the screen.

**Comment by ScrubN** [comment]
You can hide bots by adding them to the ignored users list. Hiding ASCII art isn't really possible unfortunately since the banned words list looks for words, you can't just add common ASCII art characters to it.

Instructions/examples on how to do this can be found in the [WPF Readme](https://github.com/lay295/TwitchDownloader/blob/master/TwitchDownloaderWPF/README.md#chat-render) and the [CLI Readme](https://github.com/lay295/TwitchDownloader/blob/master/TwitchDownloaderCLI/README.md#arguments-for-mode-chatrender).
