### ISSUE TITLE
[SUGGESTION] MAKE BLACK NAMES READABLE

### ISSUE THREAD

**Issue by nuketownhf** [lay295/TwitchDownloader#11]
Hello,
some users that have black colour names are non-readable
example:
[https://i.imgur.com/vFkJoIY.png](https://i.imgur.com/vFkJoIY.png)

thanks

**Comment by Insayno** [comment]
Yeah, why are some names black? Doesn't look very appealing.

**Comment by lay295** [comment]
I tried to fix it in [this](https://github.com/lay295/TwitchDownloader/commit/111dfb6abf23cefc625172be0b3cdee2ca218fc4) commit, but it didn't work very well. Their names are black because they set their names to black on Twitch. BTTV auto adjusts user color to make names look better.

I'll probably just hard code black to be grey until I can make a proper solution that works.

**Comment by ScrubN** [comment]
This was fixed in #1072
