### ISSUE TITLE
Failed to finalize video (code -12)

### ISSUE THREAD

**Issue by pb243** [lay295/TwitchDownloader#1148]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

I try to download a VOD, and when it's about to finish step 2 of download, it goes, "ERROR: Failed to finalize video (code -12), retrying in 5 seconds..." several times before quitting, directing me to where the cache is.

For the record, I was almost going to make this a reply to the "Failed to finalize video code -2," but this honestly might be a separate issue, I don't know.

### Add any related files or extra information here

These are the generated files in the cache folder:
[concat.txt](https://github.com/user-attachments/files/16171095/concat.txt)
[ffmpegLog.txt](https://github.com/user-attachments/files/16171097/ffmpegLog.txt)
[metadata.txt](https://github.com/user-attachments/files/16171098/metadata.txt)

**Comment by pb243** [comment]
In case it's helpful, this issue is only with the VOD download. All chat downloads worked fine.

**Comment by ScrubN** [comment]
There's a maximum stream count???

**Comment by Kameshennyn** [comment]
Something like this :
[concat @ 000001bcf1c7fd40] Number of streams exceeds max_streams parameter (1000), see the documentation if you wish to increase it
[in#0 @ 000001bcf1c7f940] Error opening input: Cannot allocate memory

**Comment by ScrubN** [comment]
Why does this have to be so annoying...

**Comment by ScrubN** [comment]
So it turns out that in 2016, someone filed a 5.5 medium CVE because their service blindly input user input files into FFmpeg and it caused their server to out-of-memory, and so the FFmpeg devs limited streams to 1000 by default.

After removing the limit, I can confirm that the CVE is complete BS and its the developer's fault for blindly trusting user input. Hotfix will be out soon.
![image](https://github.com/lay295/TwitchDownloader/assets/72096833/dbcc5188-7ecf-490f-8630-c8cf6672865b)

**Comment by pb243** [comment]
Thanks for the help!
