### ISSUE TITLE
Auto create the folder if it does not exist.

### ISSUE THREAD

**Issue by Mishasama** [lay295/TwitchDownloader#1171]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

![image](https://github.com/user-attachments/assets/485872a2-c2aa-416b-8ae5-ef94975a8638)

When using enqueue download, it also means the user intends to do a batch download.
And it may be necessary to use different folders to categorize the storage.

Also, since the path to the download folder can be entered manually, users can use different folders with simple modifications instead of opening the browser each time to specify the folder to use.
However, the program is not able to create folders for non-existent paths like other downloaders. Users are forced to manually create new folders one by one, which is very inconvenient.

**Comment by ScrubN** [comment]
> When using enqueue download, it also means the user intends to do a batch download.
And it may be necessary to use different folders to categorize the storage.

This can be accomplished by customizing the filename parameters. I know it isn't *super* convenient, but there isn't really a better way that's possible without rewriting the entire queue system.

> However, the program is not able to create folders for non-existent paths like other downloaders. Users are forced to manually create new folders one by one, which is very inconvenient.

You're right, showing an error message instead of creating the folder is pretty dumb.
