### ISSUE TITLE
Permanent option to set Task Queue downloads to rename/overwrite

### ISSUE THREAD

**Issue by hianick** [lay295/TwitchDownloader#1260]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

When batch downloading vods, there are often duplicate dates/titles that will overlap filenames, but you need to wait for the duplicate popup to show so you can check "remember for this session" before you're able to leave your computer while they download. There are a few ways I think this could work.

1. A global setting.
2. A radio button option on the task queue tab with Duplicate Files: "Ask", "Overwrite" or "Rename".
3. Once someone checks "remember for this session" then remember it forever, and maybe tie that decision to the global setting.

**Comment by ScrubN** [comment]
I already implemented this as a global setting, however its not in a release yet because I have been too busy to finalize everything for a release. You can build from source or download a workflow build to get access to the new feature early: https://github.com/lay295/TwitchDownloader/actions/runs/11848459577
