### ISSUE TITLE
ERROR: Unable to find thumbnail and ERROR: One or more errors occurred.

### ISSUE THREAD

**Issue by soleiluna** [lay295/TwitchDownloader#136]
This is what shows up on the log whenever I paste the link and click 'get info' on chat downloader along with a popup that says "Unable to get clip/video information. Please double check your link and try again." This goes for vods that are still currently available and viewable on twitch at the moment

**Comment by lay295** [comment]
This usually happens when a VOD is still in progress when the streamer is live. Either way you should still be able to download the VOD as it's more of a warning than an actual error, the thumbnail box just won't change.

If this isn't the case, a VOD ID that constantly does this even when the streamer isn't live would be appreciated.

**Comment by soleiluna** [comment]
Thank you for the response, the streamer wasn't live when I was trying to download the file. Here is the VOD ID: 824615868

**Comment by soleiluna** [comment]
Although I tried other vods from other channels and got the same errors

**Comment by soleiluna** [comment]
Oh I tried cleaning the cache and it started working again, thanks
