### ISSUE TITLE
Program is "unable to fetch video info"

### ISSUE THREAD

**Issue by DruidDobby** [lay295/TwitchDownloader#155]
Yo,
I've used the program smoothly previously. I tried downloading a vod recently but it returns with an error message saying:

"Unable to get the video information.
Please make sure the video ID is correct and try again."

The log also has a message saying "ERROR: The remote server returned an error: (404) Not Found."

I tried doing this with multiple vods from multiple channels, just in case this one vod wasn't working properly, however I had no success.
I also tried completely reinstalling the application, running as administrator, as well as adding the file folder as an exception in my Firewall settings (In case the 'remote server' couldn't be reached as a result of firewall or something).

![image](https://user-images.githubusercontent.com/42050428/109919699-36a8a180-7d0d-11eb-9dcd-01b95f1fb255.png)

I'm not sure if this is an issue on my end, or an issue with the program. Please advise :)

**Comment by lay295** [comment]
Update to the latest version, this was fixed in 1.39. Feel free to comment and re-open the issue if the problem persists after updating. It's working fine for me on the latest version.

![image](https://user-images.githubusercontent.com/1060681/109920693-a9236e00-7c88-11eb-9b9d-2fb1f6fd7cb8.png)

**Comment by chronoquairium** [comment]
Re-opening the issue because it's happening to me. Happened on 1.39.8.0, updated to 1.39.11, still happened. It also takes like a minute and a half for the error screen to show up, and shows no signs of doing anything until that minute passes.
![image](https://user-images.githubusercontent.com/68948661/127753074-8981a675-5cab-4828-b3c5-1509eb4afc14.png)
