### ISSUE TITLE
Bundle header version compatibility check failed 

### ISSUE THREAD

**Issue by OnlyTunesRadio** [lay295/TwitchDownloader#159]
TwitchDownloaderCLI linux 1.39.4 is failing on Ubuntu 20.04.

Error received upon trying to run TwitchDownloaderCLI:

```
voddy@voddy:~/TwitchDownloaderCLI$ ./TwitchDownloaderCLI
Failure processing application bundle.
Bundle header version compatibility check failed
A fatal error was encountered. Could not extract contents of the bundle
```

I had unziped the folder on my windows host machine and uploaded the cli file to this Ubuntu VM. 
Then preceded to follow the instructions of:
```
sudo chmod +x TwitchDownloaderCLI
```
After trying to run it with either `TwitchDownloaderCLI` or `./TwitchDownloaderCLI` i receive that error. Is this a issue on my end or an issue with the latest build for linux? 

Kind Regards
Only Tunes

**Comment by lay295** [comment]
I've tried recently automating deployment of new versions using Github Actions and messed up the zip file extensions because they were actually .tar files. I forgot to fix this earlier, so the .zip files you downloaded and extracted were actually tar files and I assume that messed up the extraction somehow. I've updated the release to actually be correct zip files.

Try re-downloading and give it a try

**Comment by OnlyTunesRadio** [comment]
Heyo,
Thanks for the quick response.  
I have tried it on a new VM and with the new files and the same problem is still happening. Which is leading me to believe that it could be a problem with my VM's and some of the dependencies that are required, Could be missing. I will continue to dig into this VM until i get it working as others that i know have all got it working its just these VM's that are playing up.

**Comment by OnlyTunesRadio** [comment]
Heyo, 
last reply. 
Turns out moving from Ubuntu 20.04.1 to 20.04.2 fixed my problem. 
Thanks for the help.
