### ISSUE TITLE
[Suggestion] Is it possible to create a realtime chat replay system?

### ISSUE THREAD

**Issue by ellieaii** [lay295/TwitchDownloader#162]
As the question suggests, is it possible to create a realtime chat replay system that reads the json file and creates a window that replays chat instead of rendering and creating a video file?

An example that I can provide is this chrome extension called "Twitch Chat Replay". Its purpose was to replay twitch chat for the anime marathons that took place a few years ago.

I'm not sure how feasible this is but I would greatly appreciate it since I can't seem to render chat properly without the program freezing or it's just simply taking long time. 

Here is the link for the [chrome extension](https://chrome.google.com/webstore/detail/twitch-chat-replay/kckepnldahdjnfmlpalbgjekincelkkk?hl=en) and its [github page](https://github.com/ahabyss/TwitchChatReplay).

**Comment by lay295** [comment]
It's certainly possible, I just haven't had time to work on this program much and besides a few quality of life things such as queueing rendering, I feel this program is mostly "complete". There are always more things I can fix and add though. Still quite a few bugs I gotta work out when I have time...

In regards to your suggestion, I feel it's out of the scope of this project as it's mainly geared towards video editors. I have an archiving website and a few people asked if they could setup something similar so over the summer I was going to make another desktop application that saved livestream and their chats. I'd probably implement some kind of replay system like you're suggesting in that, I don't plan to work on it until the summer though.

**Comment by ShurtMao** [comment]
I see, got it. Thank you so much for responding and letting me know about your plans. I'll be looking forward to it. This program has been incredibly helpful and it's quite intuitive too. I've also seen your archiving website and it's really good as well! I really appreciate your work.

I've mostly been using this program to archive livestreams and I wanted to include a chat replay, but since my computer is quite slow these days, I can't render the chat properly, or at least in a timely manner.

Out of curiosity however, do you take requests or suggestions on which streamer to add to your archiving website? I would like to suggest one, but I completely understand if it would be too much to handle since you're archiving a lot of already.

Thanks again, and I hope you have a good day.

**Comment by Kryptortio** [comment]
I was about to post this as a new issue/suggestion but I guess it's really similar to this one so I'll just add this here as a comment here instead.

# HTML render/player/viewer (like Twitch VOD player)

I think it could be nice to have the option playback the VOD and chat as you would on Twitch. With video and chat next to each other where the chat is actual text rather than a rendered video so that you can easily click links,  copy text or take advantage of the browser translate function.

The HTML file would just read the video and chat file and then output the chat according to the current time of the video. The following is an example that let's you load video and JSON separately with the chat constantly being rendered when video time changes.

<details>
  <summary>HTML example (quick and dirty, copy and save as a .html file to try)</summary>
  
```
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <title>TD player example</title>

  <style type="text/css">
body {
	overflow: hidden;
}  
video, input {
    display: inline;
}
video {
	width: 80%;
	position: absolute;
    top: 0;
    left: 0;
}
#controls {
	position: absolute;
    left: 0;
    bottom: 0;
}
#chat {
    width: 20%;
    border: 1px solid black;
    height: 100%;
    position: absolute;
    right: 0;
    top: 0;
	overflow: scroll;
}

input {
    width: 200px;       
}

.info {
    background-color: aqua;            
}

.error {
    background-color: red;
    color: white;
}
  </style>
</head>
<body>
<span id="controls">
	Video:<input id="vidinput" type="file" accept="video/*"/>
	Chat:<input id="jsoninput" type="file" accept=".json"/>
	<span id="message"></span>
</span>
<video controls autoplay></video>
<span id="chat"></span>

    <script type="text/javascript">//<![CDATA[
(function localFileVideoPlayer() {
	'use strict'
	var URL = window.URL || window.webkitURL;
	var videoNode = document.querySelector('video');
	var chatNode = document.querySelector('#chat');
	var chatJson;
	
	var displayMessage = function (message, isError) {
		var element = document.querySelector('#message')
			element.innerHTML = message
			element.className = isError ? 'error' : 'info'
	}
	var playSelectedFile = function (event) {
		var file = this.files[0]
		var type = file.type
		
		var canPlay = videoNode.canPlayType(type)
		if (canPlay === '') canPlay = 'no'
		var message = 'Can play type "' + type + '": ' + canPlay
		var isError = canPlay === 'no'
		displayMessage(message, isError);

		if (isError) {
			return;
		}

		var fileURL = URL.createObjectURL(file)
		videoNode.src = fileURL
	}
	
	var loadChat = function(event) {
        var input = event.target;

        var reader = new FileReader();
        reader.onload = function(){
		  chatJson = JSON.parse(reader.result);
		  initChat();
		  
        };
        reader.readAsText(input.files[0]);
   };

   var updateChat = function(event) {
		if(chatJson == null) return;

		let currenTime = videoNode.currentTime;
		chatNode.innerHTML = currenTime+'<br>';
		chatJson.comments.forEach(function(obj) { 
			
			if(currenTime >= obj.content_offset_seconds) {
				let chatLine = document.createElement('div');
				chatLine.innerHTML = '<b>' + obj.commenter.display_name +'</b>:'+ obj.message.body;
				chatNode.appendChild(chatLine);
			}
		});
		chatNode.scrollTop = chatNode.scrollHeight;
   }
  
  var inputNodeVideo = document.querySelector('#vidinput');
  var inputNodeChat = document.querySelector('#jsoninput');
  inputNodeVideo.addEventListener('change', playSelectedFile, false);
  inputNodeChat.addEventListener('change', loadChat, false);
  videoNode.addEventListener('timeupdate', updateChat, false);
})()
  //]]></script>
</body>
</html>
```
</details>

The example is working but it's just a test, it can be improved a lot when it comes to performance and visuals (could be made to look  and work similar to Twitch GUI). It could also rather than being a player where you load two files be outputted as a file with the VOD/chat files hard coded so you don't have to select them manually (it could be an alternative "render" option that creates one HTML file for each VOD). Might also be possible to embed the HTML into the GUI for use as a VOD viewer or just as a quick preview.

**Comment by Theotherguy1223** [comment]
> 

Is there any chance of you developing this further?
This would be the perfect solution for me, and I assume others. I just don't know enough HTML/CSS/Javascript to do it properly, and make it look similar to Twitch.

On my end, using the chat rendered makes all the text pretty blurry and hard to read, regardless of the settings. this would be perfect.
