### ISSUE TITLE
Why it takes so long to download chat?

### ISSUE THREAD

**Issue by George620** [lay295/TwitchDownloader#163]
Only question, but why it takes so long to download chat in videos with lots of text when I have 30Mb/s internet connection to download it. It's only downloading 2Mb/s max (maybe). If I look at the file size it only have 2MB and it takes at least 3 min. Why is this like that? Not my internet obviously.

**Comment by lay295** [comment]
Because with how the chat comments API works for Twitch, you can specify a time in the VOD or a "next" variable and it'll return the next 100 comments or so.

So I would like to make it faster, but I'm limited to 1 request at a time, since for the next request I need the "next" variable which is given from the previous request.

It goes like:
I ask Twitch for comments at time = 0, it returns 100 comments and "next" variable
I ask Twitch for comments at next, it returns 100 comments and "next" variable
etc until there is no next variable

I can likely parallelize it by doing multiple request at different times and combining them. Such as 0, time/2, time/4 etc and just combining them. It would add a little complexity to the logic though. So, maybe in the future.
