### ISSUE TITLE
Terrible performance compared to previous versions. Crashes

### ISSUE THREAD

**Issue by tolekk** [lay295/TwitchDownloader#18]
As in the title, the newest version of the tool completely dunked on its performance in my system for some reason. I have a Ryzen 7 2700X and before, 6h chats would render in about 4 hours, but now it takes 12. I noticed the tool only uses 1 core of my CPU for the rendering and a little bit of my GPU for some reason. Tried using -threads 16 arguments in FFmpeg options in the tool but to no effect. 
There also were crashes when rendering, but only about 2-3 hours into it. Testing another render now, we'll see what error it gives, but it had something to do with "pipe" - I can't remember more.

Below I attached my render settings. Crashes happened on MP4 H264, so I'm testing MOV right now. 

![image](https://user-images.githubusercontent.com/48994738/74603687-8098f800-50b6-11ea-8df3-49185512e4dd.png)

EDIT: UPDATE. left the rendering to itself and went to get groceries. Also noticed the program runs in 32bit mode.
![image](https://user-images.githubusercontent.com/48994738/74609013-29ab1700-50e6-11ea-8347-46ce0d4fa844.png)

![image](https://user-images.githubusercontent.com/48994738/74608672-80fbb800-50e3-11ea-8442-70c10656c9c9.png)
I wonder if this issue is only specific to my setup. If you have or don't have this issue on version 1.2 please mention it.

**Comment by lay295** [comment]
I probably made some bad change proformance wise for larger chats, when I do testing I usually stay with the default small chatbox, and maybe double the size. I checked and the proformance for me is slightly worse than the older one for rendering a video.

**Comment by lay295** [comment]
Didn't mean to close.

**Comment by tolekk** [comment]
Yeah the reason for the resolution in my case is that keying looks way better this way. I don't want to use outlines for my videos so lower resolution messes with the font. Hope you can find out what's causing this. 👌

**Comment by lay295** [comment]
I found the issue and it should render at the same speed as the previous version. Using your settings I wasn't able to render at the speeds you were claiming, but for me it is rendering at the same speed as the previous version.

If renders are too long, you can try giving 30 fps a try instead of 60. It'll look practically the same and cut the time in half. If you also have a lot of free hard drive space (and I mean a lot) you can try encoding at a smaller resolution with a transparent background with MOV + RLE and you won't have to chroma key anything out.

I'm really unsure about the crashes, it could have been because it was compiled as 32-bit which can only use 2-4GB of ram. So hopefully building it as 64-bit won't have it crash. So give the new version a shot.

**Comment by tolekk** [comment]
Great! The performance is way better thanks to the 64-bit build. There is still lots of optimizing to be done with ffmpeg but for now this is amazing.
The update introduced a small bug tho. The grey/black names disappear on the background we used up to this point, it's not an issue for black/transparent background. 
![image](https://user-images.githubusercontent.com/48994738/74729227-655bf300-5244-11ea-9111-bac4be4e5b92.png)

**Comment by lay295** [comment]
Hmmm not sure, I forgot to return a value with names but I don't know if that's the reason.

You can re-download 1.21 with the small fix and can give that a try and see if it still happens. If it still happens can you give me the RGBA value for your background?

**Comment by lay295** [comment]
Hey, still having the name issue? Can't seem to reproduce it.

**Comment by tolekk** [comment]
Sorry for the late response. It seems like the names are the same colour as the background, making them invisible after keying.
