### ISSUE TITLE
ChatRender: --output-args fails even when passing default argument string

### ISSUE THREAD

**Issue by tmarplatt** [lay295/TwitchDownloader#192]
Hello I am using TwitchDownloaderCLI 1.0.0 under Linux Mint 20.1. The tool is great, so thank you continuing its development.

The following command fails with error `Option 'c' is unknown.`. Notice that I am passing the default output args string. It fails with any args string that I try passing.

`TwitchDownloaderCLI -m ChatRender --framerate 60 -i chat.json --output-args '-c:v h264_libx264 -preset veryfast -crf 18 -pix_fmt yuv420p "{save_path}"' -o chat.mp4`

Is the --output-args syntax wrong? The documentation and CLI help do not provide example usage.

**Comment by tmarplatt** [comment]
Actually, the TwitchDownloaderCLI tool is extracted from the 1.39.9 release zip file, but it's reporting 1.0.0 in the console output. 🤷 Sounds like a bug.

**Comment by lay295** [comment]
Uhhh I just never really incremented the CLI version numbering. In regards to the argument parsing, have you tried using double quotes instead of single quotes? It's my first time really writing a command line application and I just used [another popular library](https://github.com/commandlineparser/commandline) to parse the arguments for me instead of parsing them myself.

**Comment by tmarplatt** [comment]
(About the wrong video codec library, that was my bad when copying the command line here.)

It works now! When using `--output-args='...'` TDCLI stopped showing the error message and proceeded to render the video.

Anyway that now we know a bit more about the CLI library, perhaps its syntax could be mentioned in your documentation. Thanks again!

**Comment by Stargateur** [comment]
that should be considered as a bug
