### ISSUE TITLE
Some possible suggestions for QoL use?

### ISSUE THREAD

**Issue by dozzzz02** [lay295/TwitchDownloader#20]
I had a few suggestions if you'd like to cover these?

1. Enable multiple instances, for example so I could download multiple chat jsons at the same time, currently I am downloading 6 at the same time. For VODs as well. 

2. Downloading VODs together with chats as in when you enter in a VOD you can select a chat function so that you download the jSON together with the MP4. 

3. Render video with chat? Would spare me time using something like sony vegas to render the chat with video.

**Comment by lay295** [comment]
Ahhh never commented on this issue. In regards to multiple instances I plan to have a queue system implemented eventually as mentioned in #4 so hopefully you wont need to run multiple instances and can queue up multiple things and let it run.

Honestly, with 2 and 3 I don't think I will do them. Not 2 because I think when the queue system is implemented it'll be handy enough.

I can do 3, but the problem is many people have different uses for the chat render, and would require some way for users to pick the overlay position of the chat on the video. It would probably be best left to a separate program rather than adding that specific function to a multi-tool.

Thanks for your feedback, and the progress on the queue system will be tracked in #4
