### ISSUE TITLE
When using delimiters of VideoDownload the file audio/video is desynced

### ISSUE THREAD

**Issue by SpeedK** [lay295/TwitchDownloader#209]
When specifying -b and -e params on VideoDownload mode, the output file may have duplicate frames at beginning and end of video and desync audio/video. The output file works perfect on VLC.  Re-rendering the file with ffmpeg without any particular parameters solves the issue. Is there a better way to fix this?

**Comment by lay295** [comment]
Besides re-encoding, I don't know how to fix this.

I don't re-encode by default, because I figured people might be confused why their CPU usage would be high for just a VOD downloader. Since VODs are in 10 second chunks, it might be possible just to re-encode the first and last segment, then stitch it together. It's just an idea and I haven't really tried it though.

So I don't have a solution currently, and I might test my idea later on. Sorry. I think the behavior is the same as TwitchLeecher when I last looked into it.
