### ISSUE TITLE
Chat is not rendering fully 

### ISSUE THREAD

**Issue by Nutri626** [lay295/TwitchDownloader#22]
hello , so i downloaded chat of 5 hours 52 min video and after render its 5 hours 40 min, i tried everything twice but result is same , is there limit or why its happening ? 

i downloaded like 5 hours and then last 52 min separately , its not like its ruining whole program but still 
p.s
thanks for creating this program :)

**Comment by lay295** [comment]
Could you give me a chat json of this happening?

I suspect what's going on is that in your example the first chat message happened 12 minutes into the stream. Because how it was made, had it so that it started rendering at the time of the first comment.

So if a VOD is an hour long, but the first chat message only happened 10 minutes into the stream, the resulting chat render would only be 50 minutes long.

**Comment by Nutri626** [comment]
i answered and posted  it and it disappeared or wtf is going on ? anyway , as i mentioned above i already did it (separately)  and then i deleted it , i tried it on another 5+ hours vod and chat download and render went fine so maybe it was one time thing ? i will comment if i will face it in near future , until now i will leave this topic as open

**Comment by lay295** [comment]
Just gonna close this, feel free to re-open if you run into the issue again
