### ISSUE TITLE
Website version and server optimized CLI

### ISSUE THREAD

**Issue by Jesper-Hustad** [lay295/TwitchDownloader#245]
Thanks for making this program! 
I created a site https://vodchatdownload.com/ to make the process accessible through a browser as many without windows, on mobile or without some technical knowledge still have a barrier to using this program.

The server runs on a docker container with the TwitchDownloaderCLI.
I was thinking collaborating on making optimizations for a more server optimized CLI with parallelization and in-memory storage options (faster and cheaper) could be beneficial if this is something you already wish to eventually do.

Feel free to add any comments if you have any and of course i don't have any expectations that you must be implement this as it's your open source project after all.

**Comment by lay295** [comment]
Looks cool :P

I can only really think of 2 things to optimize it for parallelization. The cache system for images was made with the assumption of no concurrency, so there are a few problems with it. I'm already planning to re-write the cache system to be more parallel and handle concurrency better.

When you say in-memory storage options I assume you mean to not write all of the .png files of the comments to the disk? Yeah it was a bad idea to do it the way I did and it's kind of a legacy thing at this point and I'm afraid to touch most of the rendering code. I want to re-write the chat rendering part, including just rendering comments on the fly instead of pre-rendering them onto the disk, but I don't think I will do it anytime soon. However this honestly would not speed things up too significantly because of the time taken in the whole process is ffmpeg encoding the video, not the overhead due to the disk IO.

So, eventually.

**Comment by Jesper-Hustad** [comment]
I should have been more clear, i meant piping the output from ffmpeg directly to stdout. AWS lambda only allows for a few MB of storage, but a lot of ram. Tough this is actually not the important.

Downloading emotes and rendering chat takes about 80% of the processing time. I'm sure you know a lot of potential optimizations, but it seems like you think it needs a complete refactoring to really increase performance?

Haven't read trough all the code as I'm not that familiar with C#, but if i find the time i could try to find some hidden optimizations.

Fetching emotes in parallel and some chat rendering speed improvements would alone make a huge difference!

**Comment by lay295** [comment]
Yeah fetching emotes should be a lot faster in the future.

About piping to stdout, you _should_ be able to just change --output-args and set pipe:1 as the output file. Something like [this](https://superkogito.github.io/blog/ffmpegpipe.html) maybe? I have not tried it but I don't see why it wouldn't work.
