### ISSUE TITLE
Chat render noticeably shorter than VOD download

### ISSUE THREAD

**Issue by PurifierUnit** [lay295/TwitchDownloader#25]
It's me again, and back so soon.  =)

Chat render from a VOD of length 57:31 has a length of only 51:12.  Chat cropping to deliberately include the VOD's full length doesn't change this.  Is this intentional?  I was expecting this to line up 1:1 with the VOD itself, so the two can be played back side-by-side or be easily spliced together.

**Comment by lay295** [comment]
This issue is a bit harder to solve, as currently the program determines when to start and end based on the first and last messages, not how long the stream went for. Currently in the .json that info isn't stored, but I can make it so it saves the VOD length on download. So for example if your stream is 20 minutes total long, but the first message only gets typed 5 minutes after your stream, and the last message 15 minutes after your stream, the resulting chat will only be 10 minutes.

I usually use this for [archiving](https://www.youtube.com/watch?v=6M9hnpl0Vuk) streamers I watch, but their chat is pretty fast so it usually isn't a problem.

I'll try and change it on the weekend to appropriately save information about the VOD into the json.

**Comment by lay295** [comment]
Should be fixed in 1.25 with newly downloaded json files.
