### ISSUE TITLE
[ENHANCEMENT] Migrate to the new API

### ISSUE THREAD

**Issue by ii89** [lay295/TwitchDownloader#251]
Currently, this project is based on Twitch v5 API which is deprecated and scheduled to be decommissioned on February 28, 2022. I would request the dev to migrate to the new API way before the deadline, to sort out any breaking change with the new API.

**Comment by lay295** [comment]
Well, I can't exactly migrate to their new API.

![image](https://user-images.githubusercontent.com/1060681/140194852-417e9c98-d843-4741-bd89-9a6c6a65a648.png)

Since basically all of the endpoints require authentication
I either have to make all users login (I really don't want to make people login for just a downloader)
Or if I wanted to use an app access token, I would have to proxy requests by like a server I control. I could setup a serverless function to handle this, but I'd rather just communicate directly to Twitch than a server I own.

So, my only real option is just to use exclusively use their GraphQL API even though you're not supposed to  ¯\\\_(ツ)_/¯
So that is what I will probably do instead of using their new API, any other suggestions are welcome.

**Comment by lay295** [comment]
> You could let people enter a client id and client secret so you can generate app access tokens.

That doesn't seem like a very good user flow, to make people register their own app. I'm pretty set on just not using the official API

**Comment by RedAero** [comment]
I for one one would be fine with logging in - Twitch Leecher just went that way, and in the process decided to neuter their entire program for "moral reasons". So now I'm here.

Perhaps make it an option? Use this API if logged in, that API if not?

**Comment by lay295** [comment]
> I for one one would be fine with logging in - Twitch Leecher just went that way, and in the process decided to neuter their entire program for "moral reasons". So now I'm here.

It seems the main reason the TwitchLeecher developer went with the new API instead of GQL is for stability reasons. Which makes sense, but anecdotally I've had about 3 breaking changes from an official Twitch API be it from suddenly an endpoint requiring authentication, to endpoints being deprecated. How many breaking changes have I seen from GQL? 0.

Their GraphQL endpoint seems a lot more powerful than their official API, with the one downside is that it's against TOS to use it and there could be breaking changes without warning. I don't want to add authentication because it seems like it would be a headache to deal with, and I don't see a reason why if I can open a Incognito Google Chrome tab and watch a VOD (aka being unauthenticated) that I should force a user to log in.

Anyways, I do not see any missing functionality in the GQL API. If they make any breaking changes, I'm pretty confident a few hours of fiddling I can fix it. I'm usually pretty fast when it comes to changes that completely break the program.

**Comment by WAZAAAAA0** [comment]
TIL whoever made Twitch Leecher lost his mind at some point.

The app previously let you to do anything with no account just like TwitchDownloader, but now it forces users to login to their twitch accounts with their ID&PW **directly within the app** instead of using tokens lol. @Timsonrobl from https://github.com/Franiac/TwitchLeecher/issues/714 pointed it out, and the developer denied the problem by saying essentially that "it's open source so security issues aren't real", attempted to compare it to logging into your Spotify account using the official Spotify client made by Spotify... and quickly locked the issue to prevent further discourse.

So, if the API is EVER going to be implemented in TD, please don't do it the way TL did, or at least make it optional lol

**Comment by benmurphy7** [comment]
I think it's worth looking into GQL again. I was using the same v5 comments endpoint `https://api.twitch.tv/v5/videos/.../comments?content_offset_seconds` but started getting 410 responses recently. It's possible cursor support may soon be gone too.

I took a look at the GQL endpoint `https://gql.twitch.tv/gql` and is looks like the same `Client-ID` header is being used. I was able to get a valid response by posting a raw payload I pulled from a request seen on a Twitch VOD

`[{"operationName":"VideoCommentsByOffsetOrCursor","variables":{"videoID":"1671375778","contentOffsetSeconds":9084},"extensions":{"persistedQuery":{"version":1,"sha256Hash":"b70a3591ff0f4e0313d126c6a1502d79a1c02baebb288227c582044aa76adf6a"}}}]`

It looks like the same `sha256Hash` works for all calls to that endpoint and I was able to get some data for other videoIDs and offsets. It looks like you can get the same support as /v5/ without needing to authenticate each user.

The project I've been working on was using the offset endpoint to send a large number of async requests and stitch them together to speed up downloads for larger chat logs, and it's nice to see this may still be supported.

**Comment by lay295** [comment]
I've already prepared for it in https://github.com/lay295/TwitchDownloader/commit/4ea98fef08b1f16272921751692dcc4b84778fd6

When the v5 API goes offline it should seamlessly switch to using the GQL endpoint (hopefully).
