### ISSUE TITLE
Automatic name generation

### ISSUE THREAD

**Issue by rak99** [lay295/TwitchDownloader#3]
Hey there, wanna start off by saying this is a great program, really well done, thank you very much for it!

This isn't necessarily an issue but could probably be a cool feature so I'll try to explain it as best I can:

When on the 'Chat Downloader' section, (this could apply to all sections, just as an example)
after pasting the link into the VOD/Clip input and clicking get info - 
you're able to see the title of the video on the left at the thumbnail section. 
when clicking download would it be possible to sort of prefill the filename with the title earlier mentioned? So if I download a clip called 'Jebaited' or something, and I click download, the filename should say jebaited, so I only have to click save? And then for the 'Chat Render' section it should just use the same filename for the mp4 file as the json file.

Sorry if this seems finicky, but I think it'd be a good feature! I have limited programming experience but from what I understand this shouldn't be too hard, I'm just not quite sure how the permissions work, if you're allowed to sort of autocomplete a name for a file on Windows. Thanks!

**Comment by lay295** [comment]
While it does sound like a good idea in theory, because VOD and Clip names can vary so much with so many different types of characters and lengths I don't think I'll implement this.

Mainly because windows is pretty picky when it comes to file names, and path length and only specific characters etc. 

Maybe in the future I can add in an option to specify your own file format similar to TwitchLeecher
