### ISSUE TITLE
cant download twitch chat render ~ Sequence contains no elements error~

### ISSUE THREAD

**Issue by JoqniX** [lay295/TwitchDownloader#327]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

hi im trying to download my vod's chat it seems i cant even download it~
i tried all the file formats and codecs, even changed the sizes etc no use, please help
![image](https://user-images.githubusercontent.com/54277349/172264718-5a6ea14e-b1bb-4e7a-9fbf-240843f92140.png)

**Comment by lay295** [comment]
Pretty sure that error happens when there are no comments in the json file. Looking at your latest VOD there are a lot of messages though. Can you upload your JSON file here?

I'm not really sure what went wrong when downloading the JSON, but redownload the chat and it should render fine.

![image](https://user-images.githubusercontent.com/1060681/172272711-8acb00e9-d986-426a-b694-12dfbb129187.png)
[[6-6-22] JoqniX - ✦ Worku stream and chill~ - Chat.txt](https://github.com/lay295/TwitchDownloader/files/8849144/6-6-22.JoqniX.-.Worku.stream.and.chill.-.Chat.txt) (You'll have to rename it to a .json since GitHub doesn't let me upload a json file)

**Comment by JoqniX** [comment]
okie here yu go! 
[[6-6-22] joqnix - ✦ Worku stream and chill~ - Chat.txt](https://github.com/lay295/TwitchDownloader/files/8854162/6-6-22.joqnix.-.Worku.stream.and.chill.-.Chat.txt)

in case if yu want the vod link here yu go - https://www.twitch.tv/videos/1496291966

**Comment by NastyFlytrap** [comment]
Hey, im having the same issue, except chat doesnt appear on the vod, even on twitch, which is weird

The vod is 7 years old, maybe it got corrupted on twitch's end?

**Comment by The-Judge** [comment]
Same issue here. Chat JSON:
[[26.07.2022] Mind_of_Judge - Anno 1800 - Heute NEUSTART - Alle DLCs (Chat).txt](https://github.com/lay295/TwitchDownloader/files/9219485/26.07.2022.Mind_of_Judge.-.Anno.1800.-.Heute.NEUSTART.-.Alle.DLCs.Chat.txt)

**Comment by ScrubN** [comment]
I believe this issue was FFZ emotes causing a fit. FFZ fixed it on their end and we added extra precautions if it happens again
