### ISSUE TITLE
Subscriber Notifications / Highlights

### ISSUE THREAD

**Issue by goldbattle** [lay295/TwitchDownloader#347]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

The highlight messages don't seem to be working in the pre-release 1.50.0  for me.
Was originally added way back here: https://github.com/lay295/TwitchDownloader/issues/19
Testing at 1:33 into [this VOD](https://www.twitch.tv/videos/1553966638) are the below results.
[1553966638_example.json.txt](https://github.com/lay295/TwitchDownloader/files/9332549/1553966638_example.json.txt)

What I see in 1.50.0 (the text seems to go out of bounds also):
![image](https://user-images.githubusercontent.com/2222562/184519671-a3db4963-1a00-4aae-a95f-9b6d0d26d1a9.png)

What I see in 1.40.7:
![image](https://user-images.githubusercontent.com/2222562/184519659-113768e5-914e-486c-818d-21b84bd80e95.png)

The message has the correct notice param:
```
"user_notice_params":{"msg-id":"resub"}
```

**Comment by lay295** [comment]
Yeah was missing sub message highlighting

**Comment by lay295** [comment]
Yeah, kinda forgot about it when rewriting the rendering code.

Added it back now and fixed it. Looks like the twitch chat API is no longer letting us know when it's a sub message though with the v5 API, and in the new GQL query they're using it doesn't tell us anything either.

![image](https://user-images.githubusercontent.com/1060681/197468775-1d1d71d0-4bab-40ca-a1c3-1fecb3b3caaf.png)

I just guess if it's a sub message now since the API is no longer telling us. I still have to double check if it tells us if it's a highlighted message. If they're not telling us it's a sub message anymore I doubt it though.

https://github.com/lay295/TwitchDownloader/blob/59741ffad607fea3b49eadc279ccbd70200c9ffa/TwitchDownloaderCore/ChatRenderer.cs#L386-L393

![image](https://user-images.githubusercontent.com/1060681/197469093-fbc77aca-42d0-4167-bf48-5174ba567ff1.png)
