### ISSUE TITLE
Is it possible to adapt the twitch downloader code to another language other than C#?

### ISSUE THREAD

**Issue by 18vijayb** [lay295/TwitchDownloader#35]
I would love to learn more about how you went about creating the twitch chat downloader to recreate a video version of the twitch chat. 

If you are open to communicating over email, my email is vijay.s.bharadwaj@gmail.com. Sorry that this isn't exactly an issue, I just had no other way of getting in contact with you.

**Comment by lay295** [comment]
What exactly did you want to know? 

Nothing I did in it was specific to C# and could be made in any language probably. As long as it has a graphics API. I just loop over the comments, render them with a graphics API (I used Skia), then I pipe it into ffmpeg where it does its magic.

**Comment by 18vijayb** [comment]
I'm trying to recreate this in Python. Your version has all the positioning of emotes, usernames, and messages to a tee, and I was curious how you were able to perfect that. I'm assuming porting several images into ffmpeg is simple enough where I can figure it out.

**Comment by lay295** [comment]
It was just constant trial and error. It used to look a lot worse. I stuck to a certain resolution while I was getting the positioning just right, and when I was happy with the positioning and wanted to add different resolutions I just scaled all the positions based on the reference resolution. 

This is what it looked like near the beginning. https://i.imgur.com/bPlHujf.png

But it'll probably be hard to learn from the chat rendering code because it really is a mess.

**Comment by 18vijayb** [comment]
I see. How did you go about positioning the emotes among text? That was something I had alot of trouble with.

**Comment by lay295** [comment]
I'm just gonna close this, but if you're interested there is another similar project being made in C++.

https://github.com/tsoding/vodus

He streams it on his Twitch channel, could hop in and watch him code sometime or ask about the project. I tuned in and he seemed pretty chill.

https://www.twitch.tv/tsoding

**Comment by 18vijayb** [comment]
Appreciate it man I’m making some pretty good progress of my own too :)
