### ISSUE TITLE
[1.50.5] - Missing msg_id field for sub messages

### ISSUE THREAD

**Issue by TheMadog24** [lay295/TwitchDownloader#393]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

When downloading chat as a JSON file, the `"msg_id":` field is now `null` for every message.
Before the update, there were different values here, including `sub`, `resub`, `subgift` and `submysterygift`.

These values are important to me, as I am making a program that uses these files for a real-time chat replay system.

**Comment by Theotherguy1223** [comment]
On top of this, I also noticed there are some fields that are missing, that are normally present, such as:
```
"msg-param-cumulative-months":
"msg-param-months":
"msg-param-multimonth-duration":
"msg-param-multimonth-tenure":
"msg-param-should-share-streak":
"msg-param-sub-plan":
"msg-param-sub-plan-name":
"msg-param-was-gifted":
```

**Comment by lay295** [comment]
Yeah, a change Twitch made to their API. The v5 chat API no longer populates those fields and in the new GQL API they're using it doesn't tell me anything about it being a sub message either. Nothing I can really do about it besides "guess" from the formatting of the message if it's a sub message or not. Kinda a pain.

It looks like they're going to kill the old API sooner rather than later. I'm going to convert the new format to the old format, but those msg_id fields will still not be populated (unless Twitch eventually decides to start sharing that info again)

Prepare for v5 chat API to go offline: https://github.com/lay295/TwitchDownloader/commit/4ea98fef08b1f16272921751692dcc4b84778fd6

Comment from #347 

> Yeah, kinda forgot about it when rewriting the rendering code.
> 
> Added it back now and fixed it. Looks like the twitch chat API is no longer letting us know when it's a sub message though with the v5 API, and in the new GQL query they're using it doesn't tell us anything either.
> 
> ![image](https://user-images.githubusercontent.com/1060681/197468775-1d1d71d0-4bab-40ca-a1c3-1fecb3b3caaf.png)
> 
> I just guess if it's a sub message now since the API is no longer telling us. I still have to double check if it tells us if it's a highlighted message. If they're not telling us it's a sub message anymore I doubt it though.
> 
> https://github.com/lay295/TwitchDownloader/blob/59741ffad607fea3b49eadc279ccbd70200c9ffa/TwitchDownloaderCore/ChatRenderer.cs#L386-L393
> 
> ![image](https://user-images.githubusercontent.com/1060681/197469093-fbc77aca-42d0-4167-bf48-5174ba567ff1.png)

**Comment by Theotherguy1223** [comment]
I see...
But "gifted" and "mysterygift" sub messages are still not included, I assume. Or they are just broken
![image](https://user-images.githubusercontent.com/12008758/198724416-0e8334c2-915d-4ab4-910c-0b51f033e186.png)
No formatting for them.

**Comment by lay295** [comment]
Yep, just haven't had time to find all iterations of the sub messages. I'll update it later today. I also don't know if Twitch still tells us if a message is highlighted I have to check.
