### ISSUE TITLE
Is there a way to use multiple cores when finalizing mp4?

### ISSUE THREAD

**Issue by Dr0mus** [lay295/TwitchDownloader#427]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates

### Write stuff here

I am checking my core usage when the program is downloading a vod and it only uses 1 core out of the 4 I have. I am using the cli version of x64 Linux. It is extremely slow when trying to finalize ~20 hours vod.

**Comment by ScrubN** [comment]
The "Finalizing MP4" stage is just using ffmpeg to combine the download parts into a single file. Since no `-threads` arg is passed to ffmpeg during that stage, it uses what it figures is the "optimal" thread count for your system, which usually isn't a very good guess. [Related StackExchange post](https://superuser.com/questions/155305/how-many-threads-does-ffmpeg-use-by-default#1196163).

I could add a `--ffmpeg-threads` argument to the program to specify the `-threads` ffmpeg arg if a user wants to override the default

**Comment by ScrubN** [comment]
I found no difference between auto, 1, and 8 threads during the finalize phase. I assume this is because it's merely copying to a new container and not recoding

**Comment by Dr0mus** [comment]
Alright ty.
