### ISSUE TITLE
Windows warns at install and Virus total says theres a Trojan in this

### ISSUE THREAD

**Issue by ESR7764** [lay295/TwitchDownloader#429]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates

### Write stuff here

Hi I downloaded this and went to install it but Windows defender blocks it and warns against installing it. So then i checked the EXE file at Virus Total and 1 vendor says it has this in it. Trojan.Injuke.Win32.26086  What is this? Should i be worried?

https://www.virustotal.com/gui/file/c6da8fb39841a2deb4b474bebb212c806ca3e672699676989b59bbd1caac4f8c

Thanks

**Comment by ESR7764** [comment]
Hi, that is probably beyond my capability/understanding. I have watched others install this on you tube videos and as soon as they click the exe the program just opens. No windows defender message. So you saying that just because its only onw virus vendor that says theres a trojan, then its just a false positive? Any windows on my computer blocking itis just becaude its an unknown/unsigned program?

**Comment by ScrubN** [comment]
To clarify, this program does not install anything on your computer; it is entirely self contained.

To further clarify the windows defender smartscreen popup, Microsoft sells a subscription service for developers to have their publisher name officially recognized in Windows with a special signature, think of it like signing a letter or government id. Unfortunately the signature service is $800USD/year or more which is insane and unreasonable for a hobby project like this.

>  I have watched others install this on youtube videos and as soon as they click the exe the program just opens. No windows defender message.

Once a user has told smartscreen to run the program anyways it will not popup again for that program. You can do this by clicking `more info` then `run anyways`

>  So you saying that just because its only one virus vendor that says theres a trojan, then its just a false positive?

In probably 75% of cases this is true but I would not always be quick to assume false positives, as it's possible whatever you scanned has an unknown type of virus. In this case though, it's a false positive.

> And windows on my computer blocking it just because its an unknown/unsigned program?

Correct.

**Comment by goldbattle** [comment]
If enough windows users use the new builds, the warning will stop popping up naturally also without signing it.

**Comment by ScrubN** [comment]
This is now resolved. I'm confident that the positive results were because we of an old library with a critical security vulnerability. As of 1.50.7 pre-release, that library has been updated to current which fixed the vulnerability. This issue can be closed.

Virustotal results:
- CLI 1.50.7 Windows: https://www.virustotal.com/gui/file/ab6817895a1b8a4f35f3165b94f2d724fd5a07422a533bd0d6256708fe773766

- GUI 1.50.7 Windows: https://www.virustotal.com/gui/file/6a1abb6020fa99738574234417d8ff9661135d7141efb6b097fba0bed17deeed

**Comment by ESR7764** [comment]
Thankyou. i ended up installing it anyway. Nothing bad happened that i know of.

**Comment by lay295** [comment]
From the very beginning people have always complained to me about Windows warning it's a virus so I don't really think the library had much to do with it.

Even the Virus Total link in the OP shows it's completely clean now so? Dunno

**Comment by ESR7764** [comment]
I just uploaded the release zip file i download the other week and now virus total says it is all good. Must of just been a case of a false positive.

**Comment by ScrubN** [comment]
> Must of just been a case of a false positive.

It was because we were using an out-of-date library with a critical vulnerability. The vulnerability is just categorized as "trojan" because of it's nature.

> From the very beginning people have always complained to me about Windows warning it's a virus so I don't really think the library had much to do with it.

I'm pretty certain **this time** was the library. When this issue was first posted 2 days after CLI cleanup was merged, I ran my a build from master through virustotal and got a clean output. The only other thing that happened between 1.50.6 and me running the build was the MacOS pubxml fix

> Here is an angry YouTube comment from 2020 telling me it's a virus

It would be really nice if antiviruses provided a proper explanation for users unfamiliar with security classifications, but that'll never happen :p
