### ISSUE TITLE
Unable to fetch windows them

### ISSUE THREAD

**Issue by fidorulz** [lay295/TwitchDownloader#444]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

I just downloaded the last non beta release and extracted all the files to a folder and when I try to launch the exe I get the error above

Im running windows 8.1

**Comment by fidorulz** [comment]
Yes 1.50.6

I downloaded release.zip
<https://github.com/lay295/TwitchDownloader/releases/download/1.50.6/release.zip>
 from https://github.com/lay295/TwitchDownloader/releases/tag/1.50.6

Unzipped the files into a folder and then tried to launch the exe
<https://github.com/lay295/TwitchDownloader/releases/download/1.50.6/release.zip>

**Comment by ScrubN** [comment]
Use 1.50.7 pre-release GUI and your issue will be gone. This has already been reported 2 other times has been fixed

**Comment by fidorulz** [comment]
It crashed when I try to launch the exe

Seems to be a kernel issue. Most likely on my end.

Since Twitchleecher is now dead trying to find alternatives and its pretty
hard

Problem signature:
  Problem Event Name: APPCRASH
  Application Name: TwitchDownloader.exe
  Application Version: 1.0.0.0
  Application Timestamp: 63557f1f
  Fault Module Name: KERNELBASE.dll
  Fault Module Version: 6.3.9600.20666
  Fault Module Timestamp: 634e41a5
  Exception Code: e0434352
  Exception Offset: 000000000000873c
  OS Version: 6.3.9600.2.0.0.768.101
  Locale ID: 1033
  Additional Information 1: 71d9
  Additional Information 2: 71d9b9bdf0b3b3f096278141b43c870d
  Additional Information 3: c446
  Additional Information 4: c446f0fc6d7374c7661a67b31489f54d

**Comment by ScrubN** [comment]
Interesting. It seems you are technical enough to use a CLI program? You can just use the CLI release. Just don't use `chatupdate` in the 1.50.7 pre-release, its pretty broken

**Comment by fidorulz** [comment]
Yeah im not great with command line stuff

BTW virus scanner really isnt liking the app lol

[image: image.png]

Thanks anyways

**Comment by lay295** [comment]
Huh... Interesting crash. I can try and spin up a Windows 8.1 VM later to see if I can reproduce it.

I was probably going to fork TwitchLeecher and "fix" it to just be in a working state and kinda just fix any major breaking bugs. One day... Because to be honest the focus of this program is the chat downloading and rendering. I've usually just pointed people to TwitchLeecher for downloading.

**Comment by fidorulz** [comment]
Yeah TwitchLeecherwas a godsend and unfortunately it's pretty much broken
now and no longer being supported

I'm surprised by the lack of alternatives. There are some programs that
work for downloading but offer much less flexibility so been experimenting
for about a day with various programs to find something close

**Comment by Drolnevar** [comment]
I'm on Win 7 (fully updated till end of service) and I get the same bug on the newest pre-release, and on the non-beta for that matter.

Problem signature:
  Problem Event Name: APPCRASH
  Application Name: TwitchDownloader.exe
  Application Version: 1.0.0.0
  Application Timestamp: 63557f1f
  Fault Module Name: KERNELBASE.dll
  Fault Module Version: 6.1.7601.24384
  Fault Module Timestamp: 5c6e248c
  Exception Code: e0434352
  Exception Offset: 000000000000be0d
  OS Version: 6.1.7601.2.1.0.256.1
  Locale ID: 1031
  Additional Information 1: c0f8
  Additional Information 2: c0f8a7009a8299d5ea07cb46193705e0
  Additional Information 3: ef27
  Additional Information 4: ef2707e52856a92caf347e626d0686e8

**Comment by ScrubN** [comment]
> I'm on Win 7 (fully updated till end of service) and I get the same bug on the newest pre-release, and on the non-beta for that matter.

If I'm understanding you right, you mean you get that kernel fault on both 1.50.6 AND 1.50.7?

**Comment by ScrubN** [comment]
> Yeah im not great with command line stuff BTW virus scanner really isnt liking the app lol
Thanks anyways

Check #429 for updates on the virus scanning issues

**Comment by Drolnevar** [comment]
> If I'm understanding you right, you mean you get that kernel fault on both 1.50.6 AND 1.50.7?

Yes, and on 1.50.6 I also get the "Unable to fetch windows theme" before the kernel fault.

**Comment by ScrubN** [comment]
> Yes, and on 1.50.6 I also get the "Unable to fetch windows theme" before the kernel fault.

Ok, I am glad to know the kernel fault is not because of the OS version check. I may have a windows 7 laptop still lying around so I'll try to find the source of the kernel fault.

Additionally the "Unable to fetch windows theme" popup was fully intentional, though in hindsight it should have just failed silently on older windows versions so that was changed in 1.50.7, hence why you don't see it anymore.

**Comment by ScrubN** [comment]
Additional thought though, it's possible the kernel fault is because of the _existence_ of the dark title bar code. Blender had some brief issues with adding the dark title bar, and in the same update they finally got it stable they also stopped supporting windows 7. If this turns out to be the case then we can make a separate pre-windows 10 compatible release using preprocessors

**Comment by ScrubN** [comment]
Found the win7 laptop. It's running version 6.1 build 7601. The GUI does not launch unless an uncaught exception in the registry key prober is properly caught and the title bar code is completely removed. In other words, we will need a separate release for pre-win10 users

**Comment by ScrubN** [comment]
Update, it no longer cares if the title bar code is there or not, meaning a separate release isn't needed? I'm so confused...

**Comment by qemjo** [comment]
Hello sir,

How to download the patch and to install it?
Sorry I'm a noob.

**Comment by qemjo** [comment]
I just found where to download it : https://github.com/lay295/TwitchDownloader/actions/runs/3551603582
and it seems to work fine on my win 8.1

**Comment by fr1ps** [comment]
> Use 1.50.7 pre-release GUI and your issue will be gone. This has already been reported 2 other times has been fixed

hi, i use 1.50.7 and this problem don`t fixed, idk what i can do with this 
![image](https://user-images.githubusercontent.com/63454095/205434294-81afaa59-b34b-4632-8d37-29f2fc3fc8a1.png)

**Comment by ScrubN** [comment]
> hi, i use 1.50.7 and this problem don`t fixed, idk what i can do with this ![image](https://user-images.githubusercontent.com/63454095/205434294-81afaa59-b34b-4632-8d37-29f2fc3fc8a1.png)

This issue thread is about theme related crashes, not video info fetch failures.

**Comment by Phenomenaut** [comment]
Ok, so i am 99% sure i have the same issue as originally mentioned in this thread where the program just crashes when you start it and displays "Unable to fetch windows theme"on the 1.50.6 version and on the 1.50.7 just crashes without displaying anything.

However i am new to github and sorry i have no idea how to apply this patch you kindly created, the one called "Yet another theme patch #447"

I feel like i have clicked on every single pixel on this page and the related ones and all i see is code or descriptions of code lol.
Its been like five years since i opened visual studios but alternatively i could probably figure out what to do if you pointed me in the right direction. But i feel like there has to be some easier way lol with all these fancy functions on this site.
Thanks in advance.

**Comment by ScrubN** [comment]
> Ok, so i am 99% sure i have the same issue as originally mentioned in this thread where the program just crashes when you start it and displays "Unable to fetch windows theme"on the 1.50.6 version and on the 1.50.7 just crashes without displaying anything.
> 
> However i am new to github and sorry i have no idea how to apply this patch you kindly created, the one called "Yet another theme patch #447"
> 
> I feel like i have clicked on every single pixel on this page and the related ones and all i see is code or descriptions of code lol. Its been like five years since i opened visual studios but alternatively i could probably figure out what to do if you pointed me in the right direction. But i feel like there has to be some easier way lol with all these fancy functions on this site. Thanks in advance.
> 
> Edit: Oh and yes i am using Windows 7 btw

Like qemjo said 5 days ago, you should be able to download the PR validation build from the log link he sent while you wait for 1.50.8.

Alternatively you can build it from the source of that branch by using the `dotnet` console command, no visual studio needed but .NET 6 and I think .NET Framework 4 will be. You can find the 2 required commands to build from source in the `build.yml` or `build-pr.yml` files. I should probably also add a section to the README later with the build instructions.
