### ISSUE TITLE
Blank/Null fields in Chat file.

### ISSUE THREAD

**Issue by TheMadog24** [lay295/TwitchDownloader#479]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

I assume this is due to the API change, and not actually a bug, but certain fields in the chat file are left as "null", or basic/blank values.

Some examples are:
```
"bio": null,
"created_at": "0001-01-01T00:00:00",
"updated_at": "0001-01-01T00:00:00",
"logo": null,
```
I know these values are not very important to the actual TwitchDownloader program, but for what I am using these files for, it would be very useful, and appreciated.

I do understand that you are limited to the API, and these fields may not be available anymore like `"user_notice_params":`, but if they still are, I would very much appreciate having them.

Edit: 
This is probably more so a feature request than a bug report, apologies about that.

**Comment by ScrubN** [comment]
GQL returns null fields and the the comments section of the chat json is more or less a direct deserialization

**Comment by TheMadog24** [comment]
> In this case the null `bio` and `logo` fields probably mean the chatter does not have their account fully setup or it's a deleted account

the `bio` and `logo` fields are `null` for ever chatter comment, across the entire file. Along with the other fields.
Tested on the latest version, across multiple videos, and channels.

**Comment by lay295** [comment]
![image](https://user-images.githubusercontent.com/1060681/208284007-a3b80ba5-aeb1-4d98-a6eb-a3a3ee1db060.png)

This is what they give us basically, not as much as the old API. I could probably at the end of the downloading process try and populate the fields with some more requests I just didn't think it was worth it because this program doesn't use them internally.

**Comment by TheMadog24** [comment]
> I could probably at the end of the downloading process try and populate the fields with some more requests I just didn't think it was worth it because this program doesn't use them internally.

If you could/would, I would be very grateful. I could definitely use them for my project. Though, I also understand if you don't want to. It's not a necessity for me either, but a nice-to-have, and a cool edition.

**Comment by ScrubN** [comment]
Though a bit late, I would like to add that I personally think we should stop serializing `user_notice_params` because there is no equivalent in GQL and thus it will always be `null` from now on.

We *could* do the guesses that we do during chatrender but then that means a whole other mess of structuring that in the download as well as handling the existing GQL chats that don't already the improvised `user_notice_params` so it just seems more worth it to discard it from future serializations (assuming it doesn't break deserialization).

If someone is writing a wrapper to handle our chats then they can copy how we make our guesses.
