### ISSUE TITLE
user_badges is empty

### ISSUE THREAD

**Issue by mrdoff** [lay295/TwitchDownloader#515]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

For some users that I know is subs to the channel the user_badges":[] is empty. For some others it populated. "user_badges":[{"_id":"premium"

**Comment by ScrubN** [comment]
That means the user has no badges.

**Comment by mrdoff** [comment]
> That means the user has no badges.

But I know for sure that many of the users with no badges are subscribers to the channel.

**Comment by ScrubN** [comment]
I guess Twitch's API occasionally does not return badges correctly. I just downloaded a chat and was able to find one instance of a subscriber without any badges. I can assure you the chat json result is a direct conversion of the Twitch API response and any missing info is the fault of Twitch's API.

**Comment by ScrubN** [comment]
GQL is undocumented and reporting issues about it, although unlikely, could result in getting banned from Twitch.
If you want to create a ticket then get a screenshot in the official VOD player and use that as your reference, since the VOD player uses GQL behind the scenes and thus the chat badges will also not be present there.
