### ISSUE TITLE
ERROR: Value cannot be null. (Parameter 'collection')

### ISSUE THREAD

**Issue by Czompi** [lay295/TwitchDownloader#622]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When I try to download chat with images embedded, it gives the following error: `ERROR: Value cannot be null. (Parameter 'collection')`
It was not present in the previous versions.

### Potential fix

I debugged a bit and found out that `bttvChannel.channelEmotes` can be null and there's no null check when [we try to add it to BTTV emotes](https://github.com/lay295/TwitchDownloader/blob/373333595db9c4d3a1dfc17eb385e6eee671873e/TwitchDownloaderCore/TwitchHelper.cs#L159).

Affected version: `1.52.2`

**Comment by ScrubN** [comment]
Can you provide the video id? It's possible the API response is different from what we're normally expecting

**Comment by ScrubN** [comment]
One of my test channels was able to trigger the error. I'll release a hotfix since this seems urgent.

**Comment by KINGMADMATTY** [comment]
i have the same error, i find github a little confusing. Has there been a fix to the error. If so what do i have to do to get it working.
Thanks for your time
Matt

**Comment by Czompi** [comment]
ScrubN fixed it a few days ago.
It will work fine in the next release.
You can use the previous version, because that is not affected.

**Comment by KINGMADMATTY** [comment]
thanks ill try that
Matt

**Comment by KINGMADMATTY** [comment]
cool, dowloaded, installed it working thanks a million

**Comment by nguyend24** [comment]
I ran into this issue last week and I've been following it since. Not sure if what I'm seeing now should be a new issue or not. It's a slightly different error from before. 

Happens when using the latest version of Ganymede, but rendering outside ganymede with **v1.52.3** works. Mentioned it in Zibbp/Ganymede#153, and referred here by @Zibbp but I'm not sure on which side the error lies since it renders fine on the CLI.

Here's a vod where this occurs. 

https://www.twitch.tv/videos/1652395872

And this is the JSON for the chat. Changed the extension to txt so it would upload.
[1652395872_fb1e4c92-bb1a-11ed-b463-0242ac130002-chat.txt](https://github.com/lay295/TwitchDownloader/files/11154809/1652395872_fb1e4c92-bb1a-11ed-b463-0242ac130002-chat.txt)

This is for chatrender.

[STATUS] - Fetching Images [1/2]
[LOG] - No valid typefaces were found for some messages.

[STATUS] - Rendering Video: 0% (0h0m12s Elapsed | 2h31m10s Remaining)Unhandled exception. System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter '**asset**'))

**Comment by ScrubN** [comment]
> I ran into this issue last week and I've been following it since. Not sure if what I'm seeing now should be a new issue or not. It's a slightly different error from before.
> 
> Happens when using the latest version of Ganymede, but rendering outside ganymede with **v1.52.3** works. Mentioned it in [Zibbp/ganymede#153](https://github.com/Zibbp/ganymede/issues/153), and referred here by @Zibbp but I'm not sure on which side the error lies since it renders fine on the CLI.
> 
> Here's a vod where this occurs.
> 
> https://www.twitch.tv/videos/1652395872
> 
> And this is the JSON for the chat. Changed the extension to txt so it would upload. [1652395872_fb1e4c92-bb1a-11ed-b463-0242ac130002-chat.txt](https://github.com/lay295/TwitchDownloader/files/11154809/1652395872_fb1e4c92-bb1a-11ed-b463-0242ac130002-chat.txt)
> 
> This is for chatrender.
> 
> [STATUS] - Fetching Images [1/2] [LOG] - No valid typefaces were found for some messages.
> 
> [STATUS] - Rendering Video: 0% (0h0m12s Elapsed | 2h31m10s Remaining)Unhandled exception. System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter '**asset**'))

This sounds like a new issue. If you can post the whole stacktrack, that would help significantly since I am unable to reproduce with the provided chat json.
