### ISSUE TITLE
Slowed Download Speed?

### ISSUE THREAD

**Issue by nguyen-anthony** [lay295/TwitchDownloader#695]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Unsure

### Describe your issue here

Just curious if there's any kind of issue with speed to download vods?
Downloading a VOD of roughly 3-4 hours in length usually took about 5 minutes. Lately it's been about 20-30 minutes.
I've checked on my end if there's been any changes to speeds in my network, but I'm not seeing anything.
Curious if this is an application thing or a server issue by chance.

Thanks,

**Comment by ScrubN** [comment]
There is a configurable network limiter in the application as of 5 versions ago. It can be configured in the settings of the windows desktop application or via an arg in the CLI.

**Comment by nguyen-anthony** [comment]
> There is a configurable network limiter in the application as of 5 versions ago. It can be configured in the settings of the windows desktop application or via an arg in the CLI.

Thank you for this info. I've adjusted the rate and will see if this helps. The default value is much slower than what my ISP provides me, so I'm assuming this was it. Will confirm and then close.

**Comment by ScrubN** [comment]
I am unable to reproduce 40,000 KB/s not saving.

Additionally we store the download speed in an Int32 which is enough to represent a limiter of 2.147 TB/s. If we used an Int16 then that would only cover 32.767MB/s, but we use an Int32.

> It would be nice to be able to disable the rate limit

I will probably do this.

**Comment by ScrubN** [comment]
The current version has a limit of 40,960KiB/s (40 MiB/s). I am not sure how fast the bandwidth limiter can theoretically process so I just put a large number. I can increase this in the next update, probably to 1Gbps (119.2 MiB/s). There is absolutely no way that twitch servers will provide more than gigabit to a single connection.

**Comment by nguyen-anthony** [comment]
Is there any desire to make this optional or remove the default value? Admittedly we didn't know this feature existed (so thanks y'all for responding here). The original issue is **resolved** here but feel free to keep this open for further discussion on increasing the limit and whatnot. Thanks everyone.

**Comment by ScrubN** [comment]
Toggle added in 774fbdc5021c9a1339efe3a419a3f15b72109f6b

**Comment by ScrubN** [comment]
The SemaphoreSlim count is controlled by the number input on the video download page. Enqueued tasks will mirror the thread count from that page.

By removing the SemaphoreSlim, you made 1023 http requests to the same endpoint in a fraction of a second. If you weren't on Twitch/Amazon's API radar before, you probably are now 😆.
I have heard from other users with faster internet than me that a single thread downloading a 1080p60 video is able to saturate over 250mbps, so assuming you're downloading the same resolution video I don't see why you were only getting 100mbps with 4 threads. The reason the download thread count is still exposed to the user is because with smaller files (160p30, 360p30 video) the bottleneck becomes disk writes and the latency of sending & receiving the http requests. To be specific, I have found from my testing that a single thread for 160p30 video tops out around 4mbps.
