### ISSUE TITLE
Unable to render old chat files

### ISSUE THREAD

**Issue by matter1770** [lay295/TwitchDownloader#728]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

![TwitchDownloaderWPF_8ZcR3RfkVA](https://github.com/lay295/TwitchDownloader/assets/43392840/f8d91b67-b6fc-4c1e-91bf-d6e9aeb1c49a)

When I try to render this chat file from an archive, the file just jumps to being completed but the rendered video file obviously doesn't play.

**Comment by ScrubN** [comment]
Post the file.

**Comment by matter1770** [comment]
https://clickityclack.co.uk/content/videos/714668076.json

**Comment by ScrubN** [comment]
This looks like a _really_ old chat. Would you be alright if I focused full support in the Chat Updater so you can modernize the chat?

**Comment by ScrubN** [comment]
Should be fixed for the next release or the workflow build asset: https://github.com/lay295/TwitchDownloader/actions/runs/5139032614

Ideally I think you should use the updater now to modernize the chat since we moved around/removed some data, but if you want to keep the old chat it should also work.

**Comment by matter1770** [comment]
both methods worked out! thank you so much for the quick response
