### ISSUE TITLE
Audio Glitch

### ISSUE THREAD

**Issue by andreazaimbri** [lay295/TwitchDownloader#739]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Audio disturbances in the vod download.

**Comment by lay295** [comment]
What's the VOD link? What program are you using to play back the file?

**Comment by andreazaimbri** [comment]
In VLC, and when I edit the video in Adobe Premiere I hear audio noise every 10 second.

**Comment by lay295** [comment]
Cool, VOD link so I can try and reproduce the issue?

**Comment by andreazaimbri** [comment]
Can I attach the downloaded video?

**Comment by ScrubN** [comment]
> Can I attach the downloaded video?

Yes you can

**Comment by andreazaimbri** [comment]
The file is too big, this is the vod link: 
https://www.twitch.tv/videos/1844285066

**Comment by andreazaimbri** [comment]
https://drive.google.com/file/d/1X2FU2Xpq_SbiwrjmuCsmY3FHEqOGmcCA/view?usp=sharing
This is the downloaded vod.

**Comment by andreazaimbri** [comment]
This problem appears when i add the video on Adobe Premiere

**Comment by ScrubN** [comment]
I do not hear the audio disturbances in the google drive previewer, nor in VLC, MPV, or Vegas Pro 17. There is also no evidence of audio disturbances from 2 different spectrograms of the audio.
![image](https://github.com/lay295/TwitchDownloader/assets/72096833/77bcbf2e-4051-4ce2-818d-2ec587024817)
![image](https://github.com/lay295/TwitchDownloader/assets/72096833/f598422a-e693-411f-874f-84596979f001)

It is most likely that either your computer just needs a reboot or your audio drivers are bad.

**Comment by andreazaimbri** [comment]
If I download the Twitch vod with the video downloader extension, I don't notice any audio problems, while if I download with the Twitch Downloader the glitches are present. I attach a link of an edited video with premiere that contain the problem: https://youtu.be/bxWKXh_pjyc

**Comment by andreazaimbri** [comment]
The audio driver in my computer is updated, and I do not have other audio issues.

**Comment by lay295** [comment]
There can be so many possible thing going wrong, but it's an issue isolated to just you.

When you uploaded it to Google Drive, Google was able to successfully decode/re-encode the file (since it has to for compression). On my computer in every program I try it decodes fine. Nobody else is reporting this, and this program has a good amount of users at this point where if there was widespread audio glitches when downloading any VOD it should be pretty well known.

Maybe something going wrong with premier? Maybe can toggle between hardware/software decoding on Premier? But again if I cannot reproduce it (which I cannot) I'm gonna close.

**Comment by Skryah** [comment]
Hi, I have this exact same issue in the same situation as him.  
Same editing program (Adobe Premiere Pro), this issue only happens with footage that comes from TwitchDownloader. Tested multiple times with footage from different channels, and footage downloaded in other computers.  
So I'm thinking the issue is not with your app but with Premiere and how it decodes audio, however, I'm out of ideas on how to fix it.
I really like using your app and would hate if it continued this way, as it is a deal breaker.
