### ISSUE TITLE
"ERROR: Video part 270-unmuted.ts failed after 10 retries"

### ISSUE THREAD

**Issue by alvy4bit** [lay295/TwitchDownloader#743]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Hey! I looked through the existing issues but I didn't find a title where they were asking about that "XXX-unmuted.ts failed" issue.

When I try to download this VOD (and many VOD's before) i get this ERROR

ERROR: Video part XXX-unmuted.ts failed after 10 retries

I tried multiple versions, have enough empty space for download and temp and always have a connection to the internet.

What could cause this?

### Add any related files or extra information here

Here is the VOD I just tried to download: https://www.twitch.tv/videos/1829414491

**Comment by ScrubN** [comment]
I was able to reproduce the error last night, though I didn't have the time to write a response. The VOD you are trying to download seems to be missing segments.
Each segment is about 10 seconds in length, so segment 270 * 10 seconds = \~45 minutes. If you go to 45 minutes in the VOD player on twitch's website you will see that it reports a "network error" ~(everything is labeled a "network error" :p)~ because twitch servers are just not returning the video segment.
Unfortunately I don't believe there is anything that can be done about this besides waiting for their servers to fix the problem.
![image](https://github.com/lay295/TwitchDownloader/assets/72096833/c2f88d7e-48fb-4d97-93b5-18489e727c15)

Thank you for the very descriptive issue report though.

**Comment by alvy4bit** [comment]
ooh thanks yeah that makes sense!!
thank you thank you
