### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by tolekk** [lay295/TwitchDownloader#78]
Since 2 days ago I've had issues with chat rendering where i get _ERROR: Object reference not set to an instance of an object._ each time i want to render out a chat. The emotes and comments get fetched and as soon as that's done I get this error. Tried re-downloading the chat, changing versions of the tool and changing my settings with no success.

**Comment by lay295** [comment]
Perhaps an emote didn't fully download in a previous chat render. Try going to %TEMP%/TwitchDownloader in your file explorer and deleting the cache folder.

**Comment by tolekk** [comment]
That worked! I suggest making a FAQ or frequent issues and fixes page for this type of stuff, would help out a lot i think. Thank you.

**Comment by lay295** [comment]
Yeah the issue has happened to me before. I should be able to have it fix itself if it ever happens to run into a corrupt emote cache image, just haven't gotten around to it. I'll try and add it in the next release. This also happens if two chats are being rendered at the same time in the downloading emojis phase.
