### ISSUE TITLE
Add NVENC Support

### ISSUE THREAD

**Issue by lay295** [lay295/TwitchDownloader#8]
Would like chat render to have NVENC support for hardware accelerated encoding. Would be a lot faster with an NVIDIA gpu. Might have to edit the ffmpeg wrapper library as I can't for the life of me get it working.

https://github.com/accord-net/framework/tree/development/Sources/Extras/Accord.Video.FFMPEG.GPL

**Comment by FlyingSligGuard** [comment]
If I may leave a suggestion, you should drop the ffmpeg wrapper completely and pipe the frames directly to a standalone ffmpeg instance. 

Before finding your program, I found another that did something similar to what you're doing with the chat render (even used the same Accord.Video.FFMPEG library). I wanted to edit the code to be able to render to a .mov file with alpha channel support. The latest stable version of the library had limited codec support, but the latest alpha version had support for multiple other codecs (no hardware encoding support, though). The problem was that it was producing invalid video files that would not play correctly on some video players and couldn't be used in Premiere/Vegas, and with the latest alpha version on NuGet being published in November of 2017, I gave up on the library. I ended up researching how ffmpeg works and found out you can feed video frames/images to a ffmpeg instance from another program, so I removed the library and redid the rendering code.

One of the advantages of using ffmpeg this way is that you're not restricted to whatever version and encoders a library decides to implement. If a newer version of ffmpeg brings faster rendering/new encoders you don't have to wait for someone to add support to it in their library. If you want, I can try to fork your code and make a pull request with standalone ffmpeg and NVENC encoding support.

**Comment by lay295** [comment]
Huh, that sounds like a great idea actually. 

Someone actually messaged me wanting alpha channel support, and I tried the alpha version of the wrapper library too and was also getting unplayable videos, glad it wasn't only me. I'll give pipping my own images directly a shot.
