### ISSUE TITLE
new functionality

### ISSUE THREAD

**Issue by Mftml** [lay295/TwitchDownloader#80]
Hi,
first of all, nice work, works very well.

If it's possible, could you add in "Vod Downloader" the possibility of load a txt file with the times you want. 
Like  00:10:00-00:15:30 , 01:20:00-01:45:00, ...
And download automatically?

Thx

**Comment by lay295** [comment]
This is the kind of niche functionality that I would not want to put into the main program, because I don't think really anybody would use it except for you.

If you have programming/scripting knowledge, it wouldn't be too hard to use the [CLI Client](https://github.com/lay295/TwitchDownloader/blob/master/TwitchDownloaderCLI/README.md) to achieve the functionality you would want.
