### ISSUE TITLE
Chat Updater removes bits and other embeds

### ISSUE THREAD

**Issue by TheMadog24** [lay295/TwitchDownloader#816]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

After Updating a chat/Json file, I noticed that it completely removed the `"twitchBits"` section from the `embeddedData`, as shown below

Left is Original file, right is "Updated" file.
![image](https://github.com/lay295/TwitchDownloader/assets/12008758/44ca4957-1424-4da3-a973-2e641de5a932)

settings used:
![image](https://github.com/lay295/TwitchDownloader/assets/12008758/740211cc-287b-41a7-8e37-a757bf515bd7)

There are also significantly less embedded emotes and badges as well.

Example:
![image](https://github.com/lay295/TwitchDownloader/assets/12008758/1c4bba65-415d-4814-8f1f-c9aff3fe30d1)
However, no embedded bits are added.

### Add any related files or extra information here

[Example JSON File.zip](https://github.com/lay295/TwitchDownloader/files/12653903/Example.JSON.File.zip)

**Comment by ScrubN** [comment]
Ah oops. GQL does not return `bits_spent` anymore so any chats between the v5 shutdown and #597 has `bits_spent` set to 0, and when implementing #572 I assumed all chats would have correct `bits_spent` values.

I don't think I will be removing the `bits_spent` check because the renderer also relies on that. Instead I will implement the fix from #597 in the chat deserializer or the updater & renderer.

**Comment by ScrubN** [comment]
Correction, the `bits_spent` fix was #520. #597 fixed an integer overflow in the first fix.
