### ISSUE TITLE
SUGGESTION: One click = download clip/vod->chat download->chat render

### ISSUE THREAD

**Issue by holndonner** [lay295/TwitchDownloader#83]
Hello!
So far awesome program. The only thing I miss, which would make my (possibly others) workflow much quicker is the ability to do the download tasks related to a video/clip at once. I think it would be awesome to just copy a video link and download the video + render the chat automatically with the given presets.

I imagine the output like
`<streamername>+" - "+<clipname>+"."+<extension>` 
`<streamername>+" - "+<clipname>+" - chat."+<extension>`

**Comment by lay295** [comment]
It's a plan for the future when I have some motivation to add some sort of queue system. It wasn't really possible before with how I wrote it but it should be easier since wrote a core library for the CLI.

In the meantime, you can achieve something similar with the example script at the bottom of the readme, but this will be put in eventually.
