### ISSUE TITLE
im an idiot and idk how to use the macos app or set it up and yes i read the readme getting started for macos

### ISSUE THREAD

**Issue by ComfortableMilk4454** [lay295/TwitchDownloader#892]
### Checklist

- [x] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates

### Write stuff here

see title, i would greatly appreciate it if someone could take a moment who knows what they're talking about to explain to me how to set up & use this program on macos with apple silicon. thanks so much and have a great day or night!

**Comment by ScrubN** [comment]
We do not yet have an Apple Silicon Arm64 binary since none of the contributors own Apple Silicon devices, however you should be able to run the Intel x64 binary with Rosetta. According to online sources, you can run the command `arch -x86_64 zsh` to start a new terminal session running under Rosetta, and from there you should be able to run TwitchDownloaderCLI via the session.

If you are having trouble with using CLI apps, please see if https://github.com/lay295/TwitchDownloader/issues/789#issuecomment-1689230243 helps. 

Please let me know if you are able to run the Intel x64 binary with Rosetta and I will add this extra step to the README.

**Comment by AIDaN80112** [comment]
<img width="682" alt="Screenshot 2023-11-19 at 6 59 43 PM" src="https://github.com/lay295/TwitchDownloader/assets/43555540/075fa587-aa88-4ad1-82d4-32b559f073a3">
this happens when i ran the arch -x86_64 zsh command :(

**Comment by AIDaN80112** [comment]
[heres](https://youtu.be/fPWnR6_Z5xI) a screen recoreding of the issue im running into.

**Comment by ScrubN** [comment]
Is your terminal open to the directory containing TwitchDownloaderCLI? The FFmpeg download command should have printed some things to the console.

**Comment by AIDaN80112** [comment]
im sorry idk what any of that means

**Comment by AIDaN80112** [comment]
wdym directory containing TwitchDownloaderCLI & TwitchDownloaderCLI is not in your PATH environment variable, your command needs to invoke it with ./TwitchDownloaderCLI?

**Comment by ScrubN** [comment]
> wdym directory containing TwitchDownloaderCLI

When you open a terminal, it defaults to your user folder: `/usr/<you>/`, or `~` for short. Let's say TDCLI is in a directory in your downloads folder: `/usr/<you>/Downloads/TwitchDownloaderCLI-1.53.4/TwitchDownloaderCLI` (or `~/Downloads/TwitchDownloaderCLI-1.53.4/TwitchDownloaderCLI`). 

You must use the `cd` command to change the current directory that your terminal is in from your user directory to the directory in your Downloads: `cd ~/Downloads/TwitchDownloaderCLI`. From there, you should be able to invoke TDCLI with the relative-path commands provided in the README.

> TwitchDownloaderCLI is not in your PATH environment variable, your command needs to invoke it with ./TwitchDownloaderCLI?

At the end of the video, you ran `TwitchDownloaderCLI videodownload --id ...`. Since TwitchDownloaderCLI isn't part of the magic string that turns executable names into commands (called PATH), you need to write out the preceding `./`: `./TwitchDownloaderCLI videodownload --id ...`.

**Comment by AIDaN80112** [comment]
oh i see. it worked thank you!

**Comment by ScrubN** [comment]
Can you please confirm if chat rendering works too? You need to download a chat beforehand then pass that into the renderer. `./TwitchDownloaderCLI chatdownload --id 1980309083 --output chat.json` `./TwitchDownloaderCLI --input chat.json --output chat.mp4`

**Comment by AIDaN80112** [comment]
i have quite a glaring issue i just started watching the vod i downloaded. what happened to the res LOL
<img width="1392" alt="Screenshot 2023-11-19 at 8 55 27 PM" src="https://github.com/lay295/TwitchDownloader/assets/43555540/59ab26b0-e777-497b-9fe5-687e6b6159e1">

**Comment by ScrubN** [comment]
Hmmm. My best guess is that it is a problem with running FFmpeg under Rosetta. We setup FFmpeg differently for the chat renderer, so if that works as expected then I have an idea that might fix the video downloader under Rosetta too.

**Comment by AIDaN80112** [comment]
nevermind the vod actually has that res i didnt watch it beforehand

**Comment by ScrubN** [comment]
Does that mean the stretching is just a problem with the screenshot?

**Comment by AIDaN80112** [comment]
no the actual vod has that res

**Comment by AIDaN80112** [comment]
i will confirm the chat thing tomorrow

**Comment by ScrubN** [comment]
I downloaded your VOD as well and the stretching is not present. The blockiness however is related to how the VOD was streamed.
![image](https://github.com/lay295/TwitchDownloader/assets/72096833/29f93b5b-d989-44bf-b1d3-ee71816889df)

**Comment by AIDaN80112** [comment]
weird when i go to the vod on twitch and click on the source quality option it shows this:
<img width="1076" alt="Screenshot 2023-11-20 at 8 37 43 AM" src="https://github.com/lay295/TwitchDownloader/assets/43555540/3482716c-ef3b-42db-9705-2d9c6f784314">

**Comment by ScrubN** [comment]
Interesting, it might be a problem with MacOS then.

**Comment by SputNikPlop** [comment]
@ScrubN I have a mac with silicon and it indeed is a macos problem that I was able to reproduce. I've found golang and rust work better on cross compilation but getting something like this to work for mac would take a considerable amount of effort.

**Comment by AIDaN80112** [comment]
chat rendering works, sorry i forgot to do that days ago lol

**Comment by ScrubN** [comment]
Actually, instead of adding Rosetta instructions, I could just compile for apple silicon. Would you be willing to test it out? https://github.com/ScrubN/TwitchDownloader/releases/tag/1.53.5

My main concern is that the colors in chat renders might be mixed up.

**Comment by AIDaN80112** [comment]
https://github.com/lay295/TwitchDownloader/assets/43555540/d4e10491-7712-43be-a6b7-65208335f998

**Comment by SputNikPlop** [comment]
> Actually, instead of adding Rosetta instructions to the README, I could just add a binary for apple silicon. Would you be willing to test it out? https://github.com/ScrubN/TwitchDownloader/releases/tag/1.53.5
> 
> You should not need to use the `arch` command before running this. My only concerns are that the colors in chat renders might be mixed up, and the FFmpeg binary downloaded through TwitchDownloaderCLI may not work?

This is working better for at least downloading on my apple silicon machine, I haven't had time to full test.

**Comment by AIDaN80112** [comment]
i cant get it set up as you can see in the video, howd you do it?

**Comment by ScrubN** [comment]
> i cant get it set up as you can see in the video, howd you do it?

You forgot to navigate your terminal to the directory containing TwitchDownloaderCLI. `cd Downloads/TwitchDownloaderCLI`

**Comment by AIDaN80112** [comment]
in what step do i put the cd part?

**Comment by SputNikPlop** [comment]
> in what step do i put the cd part?

Right after you open a new terminal window do ```cd Downloads```

**Comment by AIDaN80112** [comment]
um 
<img width="682" alt="image" src="https://github.com/lay295/TwitchDownloader/assets/43555540/202e82c6-2e54-4d6a-aa10-4c509a22759e">

**Comment by AIDaN80112** [comment]
<img width="1362" alt="image" src="https://github.com/lay295/TwitchDownloader/assets/43555540/f2455f8b-a04d-43d4-8f86-c935b7c5eb4c">

**Comment by AIDaN80112** [comment]
nvm i just had to use /Users/mrbonk/twitchdlder as the pathname not /Users/mrbonk/twitchdlder/TwitchDownloaderCLI

**Comment by SputNikPlop** [comment]
> ugh now this @SputNikPlop <img alt="image" width="682" src="https://private-user-images.githubusercontent.com/43555540/285622867-9f47db29-dc04-4912-9a73-1b5d0c3ec05b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5NjM2NDQsIm5iZiI6MTcwMDk2MzM0NCwicGF0aCI6Ii80MzU1NTU0MC8yODU2MjI4NjctOWY0N2RiMjktZGMwNC00OTEyLTlhNzMtMWI1ZDBjM2VjMDViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDAxNDkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzMTYwOTZlMTUxMTFjNjNiOTQxZjhiNjBhMzhhZmUxNzY3YmU4N2RiMTMzNWU3MTE0ODU4ODE1YjUyZTc1OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UyO2SJWznmhorp7mRz2ea8LTk_YSNCwZ45GgKHy5sjQ">

I installed ffmpeg outside the command, unsure which binary is the best since it has been so long. Maybe someone else might know or I can follow up later.

**Comment by ScrubN** [comment]
> ugh now this 

When you get the message "zsh: killed" it means it did not recognize the command. In this case, it is because you are typing the name of TwitchDownloaderCLI, not _invoking_ it. To invoke, you type `./<filename>`, which would look like `./TwitchDownloaderCLI` in this case. You got everything else correct though!

> I installed ffmpeg outside the command, unsure which binary is the best since it has been so long. Maybe someone else might know or I can follow up later.

Installing FFmpeg through homebrew is better for the entire system, but having a built in FFmpeg downloader allows us to provide a prebuilt binary that definitely supports the compilation feature flags we require, and it also makes it easier for beginners as its just 1 command.

**Comment by AIDaN80112** [comment]
<img width="682" alt="image" src="https://github.com/lay295/TwitchDownloader/assets/43555540/4ca5508a-a39f-4c41-a533-25eed975552b">
im sorry but its still not working. what am i doing wrong now?

**Comment by ScrubN** [comment]
Have you run `chmod +x TwitchDownloaderCLI` on it yet? That command enables execution for that file and must be run at least once before invoking.

**Comment by AIDaN80112** [comment]
i have

**Comment by ScrubN** [comment]
I'm sorry, but I do not know what is the problem. If you navigated to the correct directory, ran `chmod +x TwitchDownloaderCLI`, and correctly invoked TDCLI, then it should be working.

**Comment by AIDaN80112** [comment]
well it randomly started working with [this version](https://github.com/lay295/TwitchDownloader/releases/download/1.53.6/TwitchDownloaderCLI-1.53.6-MacOS-x64.zip). maybe it was because i was on beta software.
