### ISSUE TITLE
Sound hitches / gets distorted on VODs downloaded with this tool

### ISSUE THREAD

**Issue by Skryah** [lay295/TwitchDownloader#912]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Footage downloaded from this app, when fed into Adobe Premiere (and only Premiere) introduces a lot of crackles and distortion.  
The same footage downloaded in other ways does not behave this way.  
I don't think the issue is with your encoding, but with the way Premiere decodes audio. I'm out of ideas on how to fix it.
I really like using your app and would hate if it continued this way, as it is a deal breaker.

**Comment by OchreFox** [comment]
Hi, did you end up figuring out why?

**Comment by Skryah** [comment]
Yes, it's because Twitch saves their VODs server side on a really high compression audio codec that just causes issues in editing software. For my case, running it through a .mp3 encoder fixes it.

**Comment by bradyj04** [comment]
wanted to ask here, is there any fix for this, it seems to still be very noticable (preferably a fix that isnt re-encoding)

**Comment by ScrubN** [comment]
If you are experiencing the audio issues when trimming the VOD, try using
safe trimming. Otherwise, I'll need more information in a new issue thread.

**Comment by Mishasama** [comment]
> wanted to ask here, is there any fix for this, it seems to still be very noticeable (preferably a fix that isnt re-encoding)

@bradyj04 
Please provide the VOD page where the problem occurs, and include the name of the other "no problem" tool you used for the reproduction test.
It is also recommended to use audio processing software "Audacity" to check if the waveforms of the audio tracks of the two videos are the same, or "MediaInfo" to check if the encoding information is the same, in order to rule out the problem caused by the download.

👆That should be the "more information".

Theoretically, this program does not re-encode the downloaded content, unless you use the "Chat Render" function.
