### ISSUE TITLE
Quality Option is Bugged, 1080p Option Downloads 720p Videos

### ISSUE THREAD

**Issue by Brenzalor** [lay295/TwitchDownloader#938]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Whenever I download a VOD I never get the quality I selected, I tried few times with different VODs but every time I select 1080p60 I get 720p60 and I get 480p whenever I select 720p etc.

**Comment by ScrubN** [comment]
As far as I can tell, the streams are being sorted correctly, and they have the correct paths too. If you are getting the wrong resolution stream, I can only assume the problem is with Twitch without any extra information.
![image](https://github.com/lay295/TwitchDownloader/assets/72096833/025f6ab4-7366-47d5-b663-a77d84d45fbd)
![image](https://github.com/lay295/TwitchDownloader/assets/72096833/a7921095-6f6f-4a74-bcb9-72928c9501f9)

**Comment by ScrubN** [comment]
Closing due to stale.
